// useResultHistory — keep the last N AI tool results in localStorage.
//
// Built 2026-05-11. Hardened in the same session after the multi-agent
// security review surfaced three issues this rewrite addresses:
//   - MED: unbounded entry size could blow localStorage quota and
//     silently break further writes. Now byte-capped per-entry and
//     per-key, with quota-error retry that sheds oldest entries.
//   - MED: per-tab pushes saw stale React state, not freshest disk
//     state — multi-tab pushes could lose entries. Now `push` re-reads
//     from disk before merging.
//   - MED: no user-scoping of storage keys. Now optional `userScope`
//     suffix segregates entries per signed-in user, with `sweepHistoryForUser`
//     helper for logout cleanup.
//
// Storage shape:
//   { v: 1, entries: [ { id, savedAt, label, result }, ... ] }
//
// Cap: 5 entries default + 256KB per key total. FIFO eviction.
// 30-day TTL on the whole store.
//
// Privacy posture:
//   - Stored: AI output + a short label generated by the caller
//   - NOT stored: the user's raw input (CV, rejection email, JD body)
//   - Storage is the device's localStorage only — no server transit
//   - Same-origin XSS could read this (see CSP hardening backlog)

import { useCallback, useEffect, useRef, useState } from 'react';

const STORAGE_VERSION = 1;
const DEFAULT_MAX_ENTRIES = 5;
const DEFAULT_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days
const MAX_BYTES_PER_KEY = 256 * 1024; // 256KB total per tool
const MAX_BYTES_PER_ENTRY = 64 * 1024; // 64KB per single result

export interface HistoryEntry<T> {
  id: string;
  savedAt: number;
  label: string;
  result: T;
}

interface Stored<T> {
  v: number;
  entries: HistoryEntry<T>[];
}

export interface UseResultHistoryOptions {
  maxEntries?: number;
  ttlMs?: number;
  enabled?: boolean;
  /** Scope by signed-in user identity. Same rationale as useFormDraft. */
  userScope?: string;
}

export interface UseResultHistoryReturn<T> {
  entries: HistoryEntry<T>[];
  push: (entry: Omit<HistoryEntry<T>, 'savedAt'>) => void;
  remove: (id: string) => void;
  clear: () => void;
}

function buildKey(base: string, userScope?: string): string {
  if (!userScope) return base;
  return `${base}:${userScope}`;
}

function readSafe<T>(key: string, ttlMs: number): HistoryEntry<T>[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = window.localStorage.getItem(key);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as Partial<Stored<T>>;
    if (!parsed || parsed.v !== STORAGE_VERSION || !Array.isArray(parsed.entries)) {
      return [];
    }
    const cutoff = Date.now() - ttlMs;
    return parsed.entries
      .filter((e) => e && typeof e.savedAt === 'number' && e.savedAt >= cutoff)
      .filter((e) => typeof e.id === 'string' && typeof e.label === 'string');
  } catch {
    return [];
  }
}

/**
 * Best-effort write. On quota error, repeatedly drops the oldest
 * entry and retries. If writing a single entry exceeds the per-key
 * budget on its own, the entry is silently dropped (the caller's
 * payload is too large to ever fit, retrying won't help).
 */
function writeSafe<T>(key: string, entries: HistoryEntry<T>[]): boolean {
  if (typeof window === 'undefined') return false;
  let attempt = entries.slice();
  // Trim until under per-key byte budget BEFORE first write attempt.
  while (attempt.length > 0) {
    const payload: Stored<T> = { v: STORAGE_VERSION, entries: attempt };
    let serialized: string;
    try {
      serialized = JSON.stringify(payload);
    } catch {
      // Couldn't even serialize — drop oldest and retry, defensively.
      attempt.pop();
      continue;
    }
    if (serialized.length <= MAX_BYTES_PER_KEY) {
      try {
        window.localStorage.setItem(key, serialized);
        return true;
      } catch {
        // QuotaExceededError from other origins on same browser, or
        // private mode. Drop oldest and retry once before giving up.
        attempt.pop();
        continue;
      }
    } else {
      // Over budget — drop oldest.
      attempt.pop();
    }
  }
  return false;
}

export function useResultHistory<T>(
  key: string,
  options: UseResultHistoryOptions = {},
): UseResultHistoryReturn<T> {
  const {
    maxEntries = DEFAULT_MAX_ENTRIES,
    ttlMs = DEFAULT_TTL_MS,
    enabled = true,
    userScope,
  } = options;
  const scopedKey = buildKey(key, userScope);
  const [entries, setEntries] = useState<HistoryEntry<T>[]>([]);
  const ttlRef = useRef(ttlMs);
  ttlRef.current = ttlMs;

  // Load + prune on mount + when scopedKey changes (e.g. user logged in
  // mid-session, so userScope materialized).
  useEffect(() => {
    if (!enabled) return;
    setEntries(readSafe<T>(scopedKey, ttlRef.current));
  }, [scopedKey, enabled]);

  // Cross-tab sync: when another tab updates this key, refresh.
  useEffect(() => {
    if (!enabled) return;
    if (typeof window === 'undefined') return;
    const onStorage = (e: StorageEvent) => {
      if (e.key === scopedKey) {
        setEntries(readSafe<T>(scopedKey, ttlRef.current));
      }
    };
    window.addEventListener('storage', onStorage);
    return () => window.removeEventListener('storage', onStorage);
  }, [scopedKey, enabled]);

  const push = useCallback(
    (entry: Omit<HistoryEntry<T>, 'savedAt'>) => {
      if (!enabled) return;
      // Reject too-large entries up front: serialize the result and
      // check byte size. Avoids storing a 4MB Gemini hallucination
      // that would evict every previous entry to fit.
      let resultBytes = 0;
      try {
        resultBytes = JSON.stringify(entry.result).length;
      } catch {
        return; // Non-serializable result; nothing to do.
      }
      if (resultBytes > MAX_BYTES_PER_ENTRY) return;

      // Read fresh from disk so a parallel tab's push isn't clobbered.
      const fromDisk = readSafe<T>(scopedKey, ttlRef.current);
      const filtered = fromDisk.filter((e) => e.id !== entry.id);
      const next: HistoryEntry<T>[] = [
        { ...entry, savedAt: Date.now() },
        ...filtered,
      ].slice(0, maxEntries);
      writeSafe(scopedKey, next);
      // Re-read after write — write may have shed entries to fit quota.
      setEntries(readSafe<T>(scopedKey, ttlRef.current));
    },
    [scopedKey, enabled, maxEntries],
  );

  const remove = useCallback(
    (id: string) => {
      if (!enabled) return;
      const fromDisk = readSafe<T>(scopedKey, ttlRef.current);
      const next = fromDisk.filter((e) => e.id !== id);
      writeSafe(scopedKey, next);
      setEntries(next);
    },
    [scopedKey, enabled],
  );

  const clear = useCallback(() => {
    if (!enabled) return;
    setEntries([]);
    if (typeof window !== 'undefined') {
      try {
        window.localStorage.removeItem(scopedKey);
      } catch {
        // ignore
      }
    }
  }, [scopedKey, enabled]);

  return { entries, push, remove, clear };
}

/**
 * Sweep all Vantage history keys for the given user. Called on logout
 * to prevent shared-device leakage. Conservative prefix match.
 */
export function sweepHistoryForUser(userScope: string | undefined): void {
  if (typeof window === 'undefined') return;
  if (!userScope) return;
  try {
    const suffix = `:${userScope}`;
    const toRemove: string[] = [];
    for (let i = 0; i < window.localStorage.length; i += 1) {
      const k = window.localStorage.key(i);
      if (k && k.startsWith('vantage-') && k.endsWith(suffix)) {
        toRemove.push(k);
      }
    }
    toRemove.forEach((k) => window.localStorage.removeItem(k));
  } catch {
    // ignore
  }
}
