#!/usr/bin/env node
/**
 * Vantage AI MCP Server
 *
 * Exposes the Vantage AI free public tools (cover letter roast, rejection
 * email decoder, ghost job detector) as MCP tools that any MCP client
 * (Claude Desktop, Claude Code, Cursor, VS Code, Codex CLI) can call.
 *
 * Read-only by design. No paid actions. No CV file ingestion.
 * No authentication. The user's CV stays out of the MCP layer entirely.
 *
 * For full prep packs (paid), the response steers the user to the web UI
 * at https://aimvantage.uk where they can authenticate and confirm token
 * spend interactively.
 *
 * Reference: https://modelcontextprotocol.io/
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ErrorCode,
  McpError,
} from '@modelcontextprotocol/sdk/types.js';

const VANTAGE_API_BASE = process.env.VANTAGE_API_BASE || 'https://aimvantage.uk';
const USER_AGENT = '@vantage-ai/mcp-server/0.1.0';

const SERVER_NAME = 'vantage-ai';
const SERVER_VERSION = '0.1.0';

// ----------------------------------------------------------------------------
// Tool: vantage.roast_cover_letter
// ----------------------------------------------------------------------------
async function roastCoverLetter(args: { coverLetter: string }) {
  const { coverLetter } = args;
  if (typeof coverLetter !== 'string' || coverLetter.length < 80) {
    throw new McpError(ErrorCode.InvalidParams, 'coverLetter must be at least 80 chars.');
  }
  if (coverLetter.length > 8000) {
    throw new McpError(ErrorCode.InvalidParams, 'coverLetter exceeds 8000 chars.');
  }
  const res = await fetch(`${VANTAGE_API_BASE}/api/roast`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'User-Agent': USER_AGENT },
    body: JSON.stringify({ coverLetter }),
  });
  const json = (await res.json()) as { roast?: string; severityScore?: number; error?: string };
  if (!res.ok) {
    throw new McpError(ErrorCode.InternalError, json.error || `Vantage roast failed (${res.status}).`);
  }
  return {
    content: [
      {
        type: 'text' as const,
        text:
          `**Severity:** ${json.severityScore}/5\n\n` +
          `${json.roast}\n\n---\n\n` +
          `_Roast generated by Vantage AI · https://aimvantage.uk/roast · Free, no signup. ` +
          `For a tailored rewrite against a specific role, run a full prep pack at ` +
          `https://aimvantage.uk/register?source=mcp_server&utm_medium=mcp_tool&utm_campaign=roast_followup ` +
          `(10 free prep packs on signup, no card)._`,
      },
    ],
  };
}

// ----------------------------------------------------------------------------
// Tool: vantage.decode_rejection_email
// ----------------------------------------------------------------------------
async function decodeRejection(args: { rejectionEmail: string }) {
  const { rejectionEmail } = args;
  if (typeof rejectionEmail !== 'string' || rejectionEmail.length < 50) {
    throw new McpError(ErrorCode.InvalidParams, 'rejectionEmail must be at least 50 chars.');
  }
  if (rejectionEmail.length > 8000) {
    throw new McpError(ErrorCode.InvalidParams, 'rejectionEmail exceeds 8000 chars.');
  }
  const res = await fetch(`${VANTAGE_API_BASE}/api/decode-rejection`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'User-Agent': USER_AGENT },
    body: JSON.stringify({ rejectionEmail }),
  });
  const json = (await res.json()) as {
    verdict?: string;
    severity?: string;
    translation?: string;
    specificClues?: string[];
    nextMove?: string;
    error?: string;
  };
  if (!res.ok) {
    throw new McpError(ErrorCode.InternalError, json.error || `Vantage decode failed (${res.status}).`);
  }
  const clues = (json.specificClues || []).map((c, i) => `  ${i + 1}. ${c}`).join('\n');
  return {
    content: [
      {
        type: 'text' as const,
        text:
          `**Verdict:** ${json.verdict} (severity: ${json.severity})\n\n` +
          `**What they actually meant:**\n${json.translation}\n\n` +
          `**Specific clues from the email:**\n${clues || '  (none)'}\n\n` +
          `**Your next move:**\n${json.nextMove}\n\n---\n\n` +
          `_Decoded by Vantage AI · https://aimvantage.uk/decode-rejection · Free, no signup._`,
      },
    ],
  };
}

// ----------------------------------------------------------------------------
// Tool: vantage.ghost_job_check
// ----------------------------------------------------------------------------
async function ghostJobCheck(args: { jobListing: string }) {
  const { jobListing } = args;
  if (typeof jobListing !== 'string' || jobListing.length < 100) {
    throw new McpError(ErrorCode.InvalidParams, 'jobListing must be at least 100 chars.');
  }
  if (jobListing.length > 12000) {
    throw new McpError(ErrorCode.InvalidParams, 'jobListing exceeds 12000 chars.');
  }
  const res = await fetch(`${VANTAGE_API_BASE}/api/ghost-job-check`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'User-Agent': USER_AGENT },
    body: JSON.stringify({ jobListing }),
  });
  const json = (await res.json()) as {
    ghostProbability?: number;
    verdict?: string;
    summary?: string;
    tells?: string[];
    yourMove?: string;
    error?: string;
  };
  if (!res.ok) {
    throw new McpError(ErrorCode.InternalError, json.error || `Vantage ghost-check failed (${res.status}).`);
  }
  const tells = (json.tells || []).map((t, i) => `  ${i + 1}. ${t}`).join('\n');
  return {
    content: [
      {
        type: 'text' as const,
        text:
          `**Ghost probability:** ${json.ghostProbability}/100 — verdict: **${json.verdict}**\n\n` +
          `${json.summary}\n\n` +
          `**Tells:**\n${tells || '  (none)'}\n\n` +
          `**Your move:**\n${json.yourMove}\n\n---\n\n` +
          `_Analysed by Vantage AI · https://aimvantage.uk/ghost-job-check · Free, no signup._`,
      },
    ],
  };
}

// ----------------------------------------------------------------------------
// Tool: vantage.search
// ----------------------------------------------------------------------------
async function searchVantage(args: { query: string }) {
  const { query } = args;
  if (typeof query !== 'string' || !query.trim()) {
    throw new McpError(ErrorCode.InvalidParams, 'query is required.');
  }
  const url = new URL(`${VANTAGE_API_BASE}/api/search-suggest`);
  url.searchParams.set('q', query.slice(0, 200));
  const res = await fetch(url.toString(), {
    headers: { 'User-Agent': USER_AGENT },
  });
  const json = (await res.json()) as [string, string[], string[], string[]];
  if (!res.ok || !Array.isArray(json) || json.length !== 4) {
    throw new McpError(ErrorCode.InternalError, 'Vantage search failed.');
  }
  const [, labels, descriptions, urls] = json;
  if (labels.length === 0) {
    return {
      content: [
        {
          type: 'text' as const,
          text: `No matches on Vantage for "${query}". Try the catalogue: https://aimvantage.uk/tools`,
        },
      ],
    };
  }
  const lines = labels.map(
    (label, i) => `${i + 1}. **${label}** — ${descriptions[i]}\n   ${urls[i]}`
  );
  return {
    content: [
      {
        type: 'text' as const,
        text:
          `Top Vantage results for **"${query}"**:\n\n${lines.join('\n\n')}\n\n---\n\n` +
          `_Searched via Vantage AI · https://aimvantage.uk/search_`,
      },
    ],
  };
}

// ----------------------------------------------------------------------------
// Tool: vantage.steer_to_full_prep_pack
// (read-only steering — does NOT spend tokens; only constructs the URL.)
// ----------------------------------------------------------------------------
async function steerToFullPrepPack(args: { jobUrl?: string }) {
  const base = `${VANTAGE_API_BASE}/register?source=mcp_server&utm_medium=mcp_tool&utm_campaign=steer_full_prep`;
  const url = args.jobUrl
    ? `${base}&job=${encodeURIComponent(String(args.jobUrl).slice(0, 1500))}`
    : base;
  return {
    content: [
      {
        type: 'text' as const,
        text:
          `To run a **full Vantage prep pack** (company intelligence + tailored cover letter + interview ` +
          `questions + CV-to-role fit score + 5-minute pitch outline), the user must visit Vantage in their ` +
          `browser, sign in, and confirm the token spend. This MCP server intentionally does not spend tokens.\n\n` +
          `**Send the user this link:**\n\n${url}\n\n` +
          `Pricing: 10 free prep packs on signup (no card). After that, £5 = 20 prep packs (one-time, never expire).`,
      },
    ],
  };
}

// ----------------------------------------------------------------------------
// MCP Server wiring
// ----------------------------------------------------------------------------
const server = new Server(
  {
    name: SERVER_NAME,
    version: SERVER_VERSION,
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: 'vantage_roast_cover_letter',
      description:
        'Roast a cover letter for clichés, generic AI-fluff, and weak phrasing. Use when the user has pasted ' +
        'or referenced a cover letter and wants brutal-honest feedback. Returns a severity score (0-5) plus 3 ' +
        'numbered roasts each quoting a specific cliché in their text and giving the better swap. Read-only. ' +
        'No CV required. Cover letter is processed by Gemini and not persisted.',
      inputSchema: {
        type: 'object',
        properties: {
          coverLetter: {
            type: 'string',
            minLength: 80,
            maxLength: 8000,
            description: 'The full cover letter text to roast (80-8000 characters).',
          },
        },
        required: ['coverLetter'],
      },
    },
    {
      name: 'vantage_decode_rejection_email',
      description:
        "Translate a job-rejection email into the recruiter's actual meaning. Use when the user has been " +
        "rejected and wants to understand whether they were ATS-filtered, internal-hire'd over, salary-band " +
        'mismatched, or just sent a boilerplate. Returns a verdict (one of 10 categories), severity, plain-' +
        "English translation, the specific quoted phrases that gave the verdict away, and a concrete next move. " +
        'Read-only. Email content not persisted.',
      inputSchema: {
        type: 'object',
        properties: {
          rejectionEmail: {
            type: 'string',
            minLength: 50,
            maxLength: 8000,
            description: 'The rejection email body (50-8000 characters).',
          },
        },
        required: ['rejectionEmail'],
      },
    },
    {
      name: 'vantage_ghost_job_check',
      description:
        'Score how likely a job listing is a ghost job (a posting that exists but no one will be hired from). ' +
        'Use when the user has found a job listing and wants to gut-check before spending hours tailoring. ' +
        'Returns a 0-100 ghost probability, verdict (likely-real / unclear / likely-ghost), summary, the ' +
        "specific tells (clichés, suspicious salary bands, multiple seniorities collapsed into one role, " +
        'missing tech stack, generic team-intro fluff), and a recommended next move. Read-only.',
      inputSchema: {
        type: 'object',
        properties: {
          jobListing: {
            type: 'string',
            minLength: 100,
            maxLength: 12000,
            description: 'The job listing text (100-12000 characters).',
          },
        },
        required: ['jobListing'],
      },
    },
    {
      name: 'vantage_search',
      description:
        'Search Vantage AI content (free tools, ATS guides, interview-prep packs, blog posts, sample analyses, ' +
        'pricing). Use when the user asks for Vantage-specific information or you need to point them at a ' +
        'specific Vantage page rather than describe it from memory. Returns top 8 ranked results with labels, ' +
        'descriptions, and URLs.',
      inputSchema: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            description: 'The search query (1-200 characters).',
            maxLength: 200,
          },
        },
        required: ['query'],
      },
    },
    {
      name: 'vantage_steer_to_full_prep_pack',
      description:
        'Construct a sign-up link for Vantage that pre-fills the job URL (if provided). Use when the user ' +
        'explicitly asks to run a full prep pack on a specific role, or when their request requires the paid ' +
        'flow (CV upload, fit score, mock interview generation, company intelligence). This tool does NOT ' +
        'spend tokens — it returns a deep link the user must follow themselves.',
      inputSchema: {
        type: 'object',
        properties: {
          jobUrl: {
            type: 'string',
            format: 'uri',
            description: 'Optional job URL to pre-fill on the dashboard after sign-up.',
          },
        },
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: rawArgs } = request.params;
  const args = (rawArgs as Record<string, unknown>) || {};
  switch (name) {
    case 'vantage_roast_cover_letter':
      return roastCoverLetter(args as { coverLetter: string });
    case 'vantage_decode_rejection_email':
      return decodeRejection(args as { rejectionEmail: string });
    case 'vantage_ghost_job_check':
      return ghostJobCheck(args as { jobListing: string });
    case 'vantage_search':
      return searchVantage(args as { query: string });
    case 'vantage_steer_to_full_prep_pack':
      return steerToFullPrepPack(args as { jobUrl?: string });
    default:
      throw new McpError(ErrorCode.MethodNotFound, `Unknown tool: ${name}`);
  }
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  // Surface lifecycle to stderr so MCP clients can see the server started.
  console.error(`[${SERVER_NAME} v${SERVER_VERSION}] connected (stdio).`);
}

main().catch((err) => {
  console.error('Fatal MCP server error:', err);
  process.exit(1);
});
