#!/usr/bin/env node
// Prerender SEO metadata for every public sitemap URL.
//
// External audit (2026-05-08) found that all 154 sitemap URLs returned
// the homepage canonical/title/description in raw HTML. This script
// fixes that by writing a per-route dist/<path>/index.html with the
// correct route-specific metadata BEFORE Vercel deploys.
//
// How it works:
//   1. Read dist/index.html as the template (built by Vite).
//   2. For each route in the manifest:
//      - Replace <title>, <meta description>, <link canonical>,
//        og:url / og:title / og:description, twitter:title /
//        twitter:description, robots meta.
//      - Write to dist/<path>/index.html.
//   3. Programmatic routes (blog posts, samples, alternatives,
//      interview-prep companies, interview-questions roles) are
//      generated by reading the source data files at build time.
//
// Run as a postbuild step: see package.json `build` script.

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE, STATIC_ROUTES } from './seo-routes.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DIST = path.resolve(ROOT, 'dist');
const TEMPLATE_PATH = path.join(DIST, 'index.html');

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function injectSeo(html, route) {
  const canonical = `${SITE}${route.path === '/' ? '/' : route.path}`;
  const robots = route.noindex
    ? 'noindex,nofollow'
    : 'index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1';

  // Replace existing static meta with route-specific values. Each replace
  // is anchored to the existing tag pattern in index.html, so adding new
  // tags in index.html doesn't break this script.
  let out = html;

  // <title>
  out = out.replace(
    /<title>[\s\S]*?<\/title>/i,
    `<title>${escapeHtml(route.title)}</title>`,
  );

  // <meta name="description">
  out = out.replace(
    /<meta\s+name="description"\s+content="[\s\S]*?"\s*\/?>/i,
    `<meta name="description" content="${escapeHtml(route.description)}" />`,
  );

  // <link rel="canonical">
  out = out.replace(
    /<link\s+rel="canonical"\s+href="[^"]*"\s*\/?>/i,
    `<link rel="canonical" href="${canonical}" />`,
  );

  // <meta name="robots">
  out = out.replace(
    /<meta\s+name="robots"\s+content="[^"]*"\s*\/?>/i,
    `<meta name="robots" content="${robots}" />`,
  );

  // OpenGraph url + title + description
  out = out.replace(
    /<meta\s+property="og:url"\s+content="[^"]*"\s*\/?>/i,
    `<meta property="og:url" content="${canonical}" />`,
  );
  out = out.replace(
    /<meta\s+property="og:title"\s+content="[^"]*"\s*\/?>/i,
    `<meta property="og:title" content="${escapeHtml(route.title)}" />`,
  );
  out = out.replace(
    /<meta\s+property="og:description"\s+content="[^"]*"\s*\/?>/i,
    `<meta property="og:description" content="${escapeHtml(route.description)}" />`,
  );

  // Twitter
  out = out.replace(
    /<meta\s+name="twitter:title"\s+content="[^"]*"\s*\/?>/i,
    `<meta name="twitter:title" content="${escapeHtml(route.title)}" />`,
  );
  out = out.replace(
    /<meta\s+name="twitter:description"\s+content="[^"]*"\s*\/?>/i,
    `<meta name="twitter:description" content="${escapeHtml(route.description)}" />`,
  );

  return out;
}

async function loadProgrammaticRoutes() {
  // Programmatic routes are derived from data files at build time.
  // These are the highest-volume pages — getting them route-specific
  // metadata is critical for SEO consolidation.
  const routes = [];

  // Helper: extract a 'fieldName: "..."' or "fieldName: '...'" from
  // a TS source string, handling embedded quotes of the OPPOSITE
  // kind. We can't safely require() a .ts file from a Node ESM
  // script without adding a TS loader dependency, so we parse with
  // careful regex.
  function extractEntries(source, fieldNames) {
    const entries = [];
    // Quote-aware capture group: matches '...' or "..." with content
    // that may contain the opposite quote. Backreference \\1 ensures
    // the closing quote matches the opening quote.
    const quoted = `(['"\`])((?:(?!\\1)[\\s\\S])*?)\\1`;
    const fieldRegexes = fieldNames.map((name) => new RegExp(`${name}:\\s*${quoted}`, 'g'));
    // Find every block that contains all required fields. Iterate by
    // slug field as the anchor; for each, look forward to find the
    // matching title and description. Limit forward window to 4000
    // chars so we don't bleed into the next entry.
    const slugRe = new RegExp(`${fieldNames[0]}:\\s*${quoted}`, 'g');
    let m;
    while ((m = slugRe.exec(source)) !== null) {
      const start = m.index;
      const end = Math.min(start + 4000, source.length);
      const window = source.slice(start, end);
      const fields = {};
      fields[fieldNames[0]] = m[2];
      for (let i = 1; i < fieldNames.length; i += 1) {
        const re = new RegExp(`${fieldNames[i]}:\\s*${quoted}`);
        const fm = re.exec(window);
        if (fm) fields[fieldNames[i]] = fm[2];
      }
      if (fieldNames.every((n) => fields[n])) {
        entries.push(fields);
      }
    }
    return entries;
  }

  // Blog posts — read main file + optional `*Drafts.ts` companions. Drafts
  // pattern keeps the 1170-line main file from sprawling further; new
  // agent-generated post batches drop into separate files. Mirrors the
  // generate-feeds.mjs sitemap parser so prerender + sitemap stay in sync.
  // Without this loop, new draft posts get sitemap entries but no
  // prerendered HTML files (caught 2026-05-10 when blogPosts-newDrafts2.ts
  // had 5 new posts but 0 prerendered routes).
  const BLOG_FILES = [
    'src/data/blogPosts.ts',
    'src/data/blogPosts-newDrafts.ts',
    'src/data/blogPosts-newDrafts2.ts',
    'src/data/blogPosts-newDrafts3.ts',
    'src/data/blogPosts-newDrafts4.ts',
    'src/data/blogPosts-newDrafts5.ts',
    'src/data/blogPosts-newDrafts6.ts',
    'src/data/blogPosts-newDrafts7.ts',
    'src/data/blogPosts-newDrafts8.ts',
    'src/data/blogPosts-newDrafts9.ts',
    'src/data/blogPosts-newDrafts10.ts',
    'src/data/blogPosts-newDrafts11.ts',
    'src/data/blogPosts-newDrafts12.ts',
    'src/data/blogPosts-newDrafts13.ts',
    'src/data/blogPosts-newDrafts14.ts',
    'src/data/blogPosts-newDrafts15.ts',
    'src/data/blogPosts-newDrafts16.ts',
    'src/data/blogPosts-newDrafts17.ts',
    'src/data/blogPosts-newDrafts18.ts',
    'src/data/blogPosts-newDrafts19.ts',
    'src/data/blogPosts-newDrafts20.ts',
    'src/data/blogPosts-newDrafts21.ts',
    'src/data/blogPosts-newDrafts22.ts',
    'src/data/blogPosts-newDrafts23.ts',
    'src/data/blogPosts-newDrafts24.ts',
    'src/data/blogPosts-newDrafts25.ts',
    'src/data/blogPosts-newDrafts26.ts',
    'src/data/blogPosts-newDrafts27.ts',
    'src/data/blogPosts-newDrafts28.ts',
    'src/data/blogPosts-newDrafts29.ts',
    'src/data/blogPosts-newDrafts30.ts',
    'src/data/blogPosts-newDrafts31.ts',
    'src/data/blogPosts-newDrafts32.ts',
    'src/data/blogPosts-newDrafts33.ts',
  ];
  const seenSlugs = new Set();
  for (const blogFile of BLOG_FILES) {
    try {
      const blogTs = await fs.readFile(path.join(ROOT, blogFile), 'utf8');
      const entries = extractEntries(blogTs, ['slug', 'title', 'description']);
      for (const { slug, title, description } of entries) {
        if (seenSlugs.has(slug)) continue;
        seenSlugs.add(slug);
        routes.push({
          path: `/blog/${slug}`,
          title: `${title} | Vantage AI Blog`,
          description: (description || '').slice(0, 200),
          type: 'article',
        });
      }
    } catch (err) {
      // Drafts files are optional — main file is required.
      if (blogFile === 'src/data/blogPosts.ts') {
        console.warn('Could not parse blogPosts.ts:', err?.message);
      }
    }
  }

  // Sample analyses
  try {
    const sampleTs = await fs.readFile(
      path.join(ROOT, 'src/data/sampleAnalyses.ts'),
      'utf8',
    );
    const entries = extractEntries(sampleTs, ['slug', 'title', 'description']);
    for (const { slug, title, description } of entries) {
      routes.push({
        path: `/sample/${slug}`,
        title: `${title} | Vantage AI Sample`,
        description: (description || '').slice(0, 200),
        type: 'article',
      });
    }
  } catch (err) {
    console.warn('Could not parse sampleAnalyses.ts:', err?.message);
  }

  // Alternatives
  try {
    const altsTs = await fs.readFile(
      path.join(ROOT, 'src/components/AlternativesPage.tsx'),
      'utf8',
    );
    const entries = extractEntries(altsTs, ['slug', 'name']);
    for (const { slug, name } of entries) {
      routes.push({
        path: `/alternatives/${slug}`,
        title: `${name} Alternative — Vantage AI Compared | Vantage`,
        description: `Honest side-by-side comparison of Vantage AI vs ${name}. Where each tool wins, where each loses, and which is the better fit for your job hunt.`,
      });
    }
  } catch (err) {
    console.warn('Could not parse AlternativesPage.tsx:', err?.message);
  }

  // Company packs (interview-prep)
  try {
    const packsTs = await fs.readFile(
      path.join(ROOT, 'src/data/companyPacks.ts'),
      'utf8',
    );
    const entries = extractEntries(packsTs, ['slug', 'company']);
    for (const { slug, company } of entries) {
      routes.push({
        path: `/interview-prep/${slug}`,
        title: `${company} Interview Questions & Prep (2026) | Vantage AI`,
        description: `Free ${company} interview prep pack: signature interview pattern, 12 likely questions, common mistakes, prep routine. Free guide, no signup.`,
      });
    }
  } catch (err) {
    console.warn('Could not parse companyPacks.ts:', err?.message);
  }

  // ATS vendor pages
  try {
    const atsTs = await fs.readFile(
      path.join(ROOT, 'src/data/atsVendors.ts'),
      'utf8',
    );
    const entries = extractEntries(atsTs, ['slug', 'name']);
    for (const { slug, name } of entries) {
      routes.push({
        path: `/ats/${slug}`,
        title: `${name} resume parser: how it reads your CV (and what to fix) | Vantage`,
        description: `How the ${name} ATS parses CVs in 2026. Specific parse quirks, common failures, and the fixes that actually work. Free multi-vendor scanner included.`,
      });
    }
  } catch (err) {
    console.warn('Could not parse atsVendors.ts:', err?.message);
  }

  // Laid-off-from-<company> pages
  try {
    const laidOffTs = await fs.readFile(
      path.join(ROOT, 'src/data/laidOffCompanies.ts'),
      'utf8',
    );
    const entries = extractEntries(laidOffTs, ['slug', 'name']);
    for (const { slug, name } of entries) {
      routes.push({
        path: `/laid-off/from/${slug}`,
        title: `Just laid off from ${name}? 2026 cohort playbook | Vantage`,
        description: `Cohort-specific playbook for the 2026 ${name} layoffs: CV fixes, warm-intro framework, interview prep. Free AI tools included. By a UK indie founder.`,
      });
    }
  } catch (err) {
    console.warn('Could not parse laidOffCompanies.ts:', err?.message);
  }

  // Company × seniority cells (top 8 companies × 5 seniorities = up to 40 cells).
  // The data file has the shape:
  //   { companySlug: 'google', variants: [ { slug: 'junior', ... }, ... ] }
  // We iterate each companySlug block, then within its window collect every
  // child `slug:` (which represents a SeniorityVariant). The window ends at
  // the next companySlug occurrence (or end-of-file).
  try {
    const senTs = await fs.readFile(
      path.join(ROOT, 'src/data/companySeniorityPacks.ts'),
      'utf8',
    );
    const companyRe = /companySlug:\s*['"`]([^'"`]+)['"`]/g;
    const companyMatches = [];
    let cm;
    while ((cm = companyRe.exec(senTs)) !== null) {
      companyMatches.push({ slug: cm[1], index: cm.index });
    }
    for (let i = 0; i < companyMatches.length; i += 1) {
      const start = companyMatches[i].index;
      const end = i + 1 < companyMatches.length ? companyMatches[i + 1].index : senTs.length;
      const window = senTs.slice(start, end);
      const companySlug = companyMatches[i].slug;
      const slugRe = /\bslug:\s*['"`]([^'"`]+)['"`]/g;
      let sm;
      while ((sm = slugRe.exec(window)) !== null) {
        const seniority = sm[1];
        // Skip the companySlug match itself if it leaks in. Only accept
        // known seniority slugs from the SenioritySlug union.
        if (!['junior', 'mid', 'senior', 'staff', 'manager'].includes(seniority)) continue;
        const companyName = companySlug.charAt(0).toUpperCase() + companySlug.slice(1);
        const seniorityLabel = seniority.charAt(0).toUpperCase() + seniority.slice(1);
        routes.push({
          path: `/interview-prep/${companySlug}/${seniority}`,
          title: `${companyName} ${seniorityLabel} Interview Prep (2026) | Vantage`,
          description: `${companyName} ${seniorityLabel} interview pattern, signature questions, level rubric, comp range, common gaps. Free guide, no signup.`,
        });
      }
    }
  } catch (err) {
    console.warn('Could not parse companySeniorityPacks.ts:', err?.message);
  }

  // Interview questions by role
  try {
    const rolesTs = await fs.readFile(
      path.join(ROOT, 'src/data/interviewQuestions.ts'),
      'utf8',
    );
    const entries = extractEntries(rolesTs, ['slug', 'role']);
    for (const { slug, role } of entries) {
      routes.push({
        path: `/interview-questions/${slug}`,
        title: `${role} Interview Questions (2026 Prep Pack) | Vantage AI`,
        description: `Free ${role} interview question bank: 12 most-asked questions, model answers, prep tips, follow-up questions. No signup.`,
      });
    }
  } catch (err) {
    console.warn('Could not parse interviewQuestions.ts:', err?.message);
  }

  return routes;
}

async function main() {
  console.log('[prerender-seo] Reading template:', TEMPLATE_PATH);
  const template = await fs.readFile(TEMPLATE_PATH, 'utf8');

  const programmatic = await loadProgrammaticRoutes();
  const allRoutes = [...STATIC_ROUTES, ...programmatic];

  console.log(`[prerender-seo] Generating ${allRoutes.length} route-specific HTML files`);

  let written = 0;
  for (const route of allRoutes) {
    if (route.path === '/') {
      // Homepage — overwrite the template at dist/index.html in place.
      const out = injectSeo(template, route);
      await fs.writeFile(TEMPLATE_PATH, out);
      written += 1;
      continue;
    }
    const cleanPath = route.path.replace(/^\//, '').replace(/\/$/, '');
    const outDir = path.join(DIST, cleanPath);
    await fs.mkdir(outDir, { recursive: true });
    const outFile = path.join(outDir, 'index.html');
    const out = injectSeo(template, route);
    await fs.writeFile(outFile, out);
    written += 1;
  }

  console.log(`[prerender-seo] Wrote ${written} files.`);
}

main().catch((err) => {
  console.error('[prerender-seo] Failed:', err);
  process.exit(1);
});
